### ISSUE TITLE
Changing Scapegoat version doesn't work

### ISSUE THREAD

**Issue by mccartney** [eugene-sy/gradle-scapegoat-plugin#2]
TLDR: I tried changing Scapegoat version `1.4.4` to `1.4.6` in Gradle configuration and it still took `1.4.4`.

Or you can even try a non-existing version of Scapegoat and it still takes 1.4.4:
## Steps to reproduce
```
cd example/app-groovy
sed -i 's/1.4.4/1.4.9999/' build.gradle
./gradlew build
```
should fail, while it works (reports problems using Scapegoat `1.4.4`)

**Comment by mccartney** [comment]
Actually other values in the `scapegoat {` section of the configuration don't work either (e.g. changing the Scala version to some non-sense also yields the same outcome).

**Wild guess** (I am a Gradle newbie): is this https://stackoverflow.com/a/46383621/118587 the same reason?

**Comment by eugene-sy** [comment]
Thank you for reporting this. It definitely should be fixed!

I left the company that used gradle for scala and had never tested it in the real battle environment. Shame on me, I did not really test it properly on my local.

**Comment by mccartney** [comment]
I tried troubleshooting this, but simply the "setters" for `scapegoatVersion` are never called.

**Comment by eugene-sy** [comment]
Yeah, I run a few experiments tonight. 
`scapegoatVersion` and `scalaVersion` are not available from the configuration when I expect.
I have a solution now. 

The next version will have this and the #1 issue solved.
